name: Deploy React App to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code from GitHub
      - name: Checkout code
        uses: actions/checkout@v2

      # Create SSH private key file
      - name: Create SSH private key file
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > thinhubuntu.pem
          chmod 600 thinhubuntu.pem

      # Copy SSH private key file to GitHub Actions runner
      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i thinhubuntu.pem ubuntu@${{ secrets.EC2_IP }} << 'EOF'
            export PATH=$PATH:/home/ubuntu/.nvm/versions/node/v18.20.5/bin/yarn
            cd /home/ubuntu/practice-react
          
            git pull origin master
          
            yarn install
            yarn build
          
            sudo rm -rf /var/www/vhosts/frontend/*
            sudo cp -R dist /var/www/vhosts/frontend/
            sudo systemctl restart nginx
          EOF
